name: 'npm Version and Publish'
author: Bitovi
description: 'Version and publish your npm package'
branding:
  icon: tag
  color: red
inputs:
  update_type:
    description: "The version segment to increment: major, minor, or patch."
    required: true
    default: 'patch'
  publish:
    default: "Publish the package"
    required: false
    default: true
  npm_token:
    description: "npm Secrets token"
    required: true

runs:
  using: "composite"
  steps:
      - name: Tag and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ github.event.inputs.update_type }} -m "Publish v%s"
          git push --tags
         
      - name: Publish to NPM Registry
        if: ${{ github.event.inputs.publish == 'true' }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ github.event.inputs.npm_token }}


