name: 'npm Version and Publish'
author: Bitovi
description: 'Version and publish your npm package'
branding:
  icon: tag
  color: red
inputs:
  update_type:
    description: "The version segment to increment: major, minor, or patch."
    required: true
    default: 'patch'
  publish:
    description: "Publish the package"
    required: false
    default: 'true'
  npm_token:
    description: "npm Secrets token"
    required: true
  git_user_name:
    description: "Git username for commits"
    required: false
    default: 'Bitovi Automation'
  git_user_email:
    description: "Git email for commits"
    required: false
    default: 'os@bitovi.com'

runs:
  using: "composite"
  steps:
    - id: Tag-push
      shell: bash
      run: |
        git init
        git config user.name "${{ inputs.git_user_name }}"
        git config user.email "${{ inputs.git_user_email }}"
        npm version ${{ inputs.update_type }} -m "Publish v%s"
        # git push --tags

    - name: Publish to NPM Registry
      if: ${{ inputs.publish == 'true' }}
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ inputs.npm_token }}
