name: 'npm Version and Publish'
author: Bitovi
description: 'Version and publish your npm package'
branding:
  icon: tag
  color: red
inputs:
  update_type:
    description: "The version segment to increment: major, minor, or patch."
    required: true
    default: 'patch'
  publish:
    description: "Publish the package"
    required: false
    default: 'true'
  npm_token:
    description: "npm Secrets token"
    required: true

runs:
  using: "composite"
  steps:
      - id: Tag-push
        shell: bash
        run: |
          git config user.name os@bitovi.com
          git config user.email os@bitovi.com
          npm version ${{ github.event.inputs.update_type }} -m "Publish v%s"
          # git push --tags
         
      - name: Publish to NPM Registry
        if: ${{ github.event.inputs.publish == 'true' }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ github.event.inputs.npm_token }}


